[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
api = { path = "../api" }
agent = { path = "../agent" }
adapter-google = { path = "../adapters/google" }
adapter-ubereats = { path = "../adapters/ubereats" }
axum.workspace = true
common = { path = "../common" }
llm-client = { path = "../llm_client" }
notifier = { path = "../notifier" }
poster = { path = "../poster" }
tokio.workspace = true
tracing.workspace = true
tokio-util = "0.7"

